---
- name: install docker-py workaround
  sudo: yes
  pip: name=docker-py

- name: start redis container
  docker:
    docker_api_version: 1.19
    name: "{{ container_name }}"
    image: redis
    state: reloaded
    ports:
      - "6379:6379"
